/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.CommunityAdmin.CommunityAdmin;

import Business.Hospital.Hospital;
import Business.Doctor.Doctor;
import Business.EcoSystem;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ManageCommunityAdmins extends javax.swing.JPanel {

    /**
     * Creates new form UpdateCustomerDetails
     */
    JPanel userProcessContainer;
    EcoSystem system;
    
    public ManageCommunityAdmins(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        this.populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurants = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lbPassword = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lbUsername = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        lbRestaurant = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lbPassword1 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        CbxCommunity = new javax.swing.JComboBox<>();
        lbPassword3 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CbxCity = new javax.swing.JComboBox<>();
        CbxGender = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Manage CommunityAdmin Details");
        add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 36, 420, -1));

        tblRestaurants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Community Admin Name", "Username", "Gender", "Age", "Address", "City", "Community", "Phone Number"
            }
        ));
        jScrollPane1.setViewportView(tblRestaurants);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 800, 96));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, 65, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, -1, -1));

        btnSubmit.setText("Update");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        lbPassword.setText("Phone Number :");
        add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        lbName.setText("Username :");
        add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        txtUserName.setEditable(false);
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 159, -1));

        lbUsername.setText("Community :");
        add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 159, -1));

        lbRestaurant.setText("CommunityAdmin Name :");
        add(lbRestaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        txtPhoneNumber.setPreferredSize(new java.awt.Dimension(124, 23));
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 159, -1));

        lbPassword1.setText("Address :");
        add(lbPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 159, -1));

        CbxCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Mission Hill", "Jamaica Plain", "Huntington Avenue", "Bolyston" }));
        CbxCommunity.setPreferredSize(new java.awt.Dimension(124, 23));
        add(CbxCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 159, -1));

        lbPassword3.setText("Age :");
        add(lbPassword3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        txtAge.setPreferredSize(new java.awt.Dimension(124, 23));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 159, -1));

        jLabel11.setText("City :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        CbxCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Boston", "New York" }));
        CbxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxCityActionPerformed(evt);
            }
        });
        add(CbxCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 159, -1));

        CbxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Male", "Female" }));
        add(CbxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 159, -1));

        jLabel13.setText("Gender :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 60, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        Component[] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof SystemAdminWorkAreaJPanel){
                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                systemAdminWorkAreaJPanel.populateTree();
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    boolean isValidAttribute(String attribute, String reg){
        
        Pattern pat = Pattern.compile(reg);
        Matcher mat = pat.matcher(attribute);
        return mat.matches();
    }
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblRestaurants.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblRestaurants.getModel();
        
        String Namereg = "^[\\p{L} .'-]+$";
        String UserNamereg = "^(?=[a-zA-Z0-9._]{8,20}$)(?!.*[_.]{2})[^_.].*[^_.]$";
        String Hnumreg = "^\\d{1,6}\\040([A-Z]{1}[a-z]{1,}\\040[A-Z]{1}[a-z]{1,})$|^\\d{1,6}\\040([A-Z]{1}[a-z]{1,}\\040[A-Z]{1}[a-z]{1,}\\040[A-Z]{1}[a-z]{1,})$|^\\d{1,6}\\040([A-Z]{1}[a-z]{1,}\\040[A-Z]{1}[a-z]{1,}\\040[A-Z]{1}[a-z]{1,}\\040[A-Z]{1}[a-z]{1,})$";
        String phonereg = "[0-9]{10}";
        String passreg = "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$";
//        At least one upper case English letter, (?=.*?[A-Z])
//        At least one lower case English letter, (?=.*?[a-z])
//        At least one digit, (?=.*?[0-9])
//        At least one special character, (?=.*?[#?!@$%^&*-])
//        Minimum eight in length .{8,} (with the anchors)
        
        String Name = txtName.getText();
        String UserName = txtUserName.getText();
        
      
        String Gender = (String)CbxGender.getSelectedItem();
        String Hnum = txtAddress.getText();
        String comm = (String)CbxCommunity.getSelectedItem();
        String city = (String)CbxCity.getSelectedItem();
        int Age;
        String Phone = txtPhoneNumber.getText();
        String Hsptname = txtName.getText();
        
        if(!isValidAttribute(Name,Namereg)){
            JOptionPane.showMessageDialog(this, "Invalid name input:" + Name, "Warning",
        JOptionPane.WARNING_MESSAGE);
           return;
        }
       
        
        if(CbxGender.getSelectedIndex() == 0){
                        JOptionPane.showMessageDialog(this, "Please select Gender" ,"Warning",
        JOptionPane.WARNING_MESSAGE);
           return;
        }
        if(!isValidAttribute(Hnum,Hnumreg)){
            JOptionPane.showMessageDialog(this, "Invalid House number input:" + Hnum, "Warning",
        JOptionPane.WARNING_MESSAGE);
           return;
        }
        if(CbxCommunity.getSelectedIndex() == 0){
                        JOptionPane.showMessageDialog(this, "Please select Community" ,"Warning",
        JOptionPane.WARNING_MESSAGE);
           return;
        }
        if(CbxCity.getSelectedIndex() == 0){
                        JOptionPane.showMessageDialog(this, "Please select City" ,"Warning",
        JOptionPane.WARNING_MESSAGE);
           return;
        }
       
        try{
          Age = Integer.parseInt(txtAge.getText());

        }catch (NumberFormatException ex){

             
             JOptionPane.showMessageDialog(this, "\"Invalid input : Age is not a number\"", "Warning",
        JOptionPane.WARNING_MESSAGE);
             return;
        }
        if(Age < 0){
            JOptionPane.showMessageDialog(this, "\"Invalid input : Age cannot be negative\"", "Warning",
        JOptionPane.WARNING_MESSAGE);
             return;
        }
        if(!isValidAttribute(Phone,phonereg)){
           JOptionPane.showMessageDialog(this, "Invalid phone input:" + Phone, "Warning",
        JOptionPane.WARNING_MESSAGE);
           return;
        }
        
        
        
        
        
        
        String userName = txtUserName.getText();
        
        String phoneNumber = txtPhoneNumber.getText();
        String address = txtAddress.getText();
        
        ArrayList<CommunityAdmin> Cads = system.getCommunityAdminDirectory().returnCommunityAdminDetails();
        for(CommunityAdmin c: Cads)
        {
            if(c.getUserName().equals(userName))
            {
               c.setAge(Age);
               c.setName(txtName.getText());
               c.setGender(Gender);
               c.setCommunity((String)CbxCommunity.getSelectedItem());
               c.setPhoneNumber(txtPhoneNumber.getText());
               c.setAddress(txtAddress.getText());
               break;
            }
            
        }
        
        JOptionPane.showMessageDialog(this, "Updated the details successfully");
        txtUserName.setText("");txtName.setText("");
        txtAddress.setText("");txtPhoneNumber.setText("");
        txtAge.setText("");
        CbxGender.setSelectedIndex(0);
        CbxCommunity.setSelectedIndex(0);
        CbxCity.setSelectedIndex(0);
        populateTable();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
          int selectedRowIndex = tblRestaurants.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to View");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblRestaurants.getModel();
        CommunityAdmin selectedCommunityAdmin = (CommunityAdmin)model.getValueAt(selectedRowIndex, 0);
        txtUserName.setText("");
        txtUserName.setText(selectedCommunityAdmin.getUserName());
      
        txtName.setText("");
        txtName.setText(selectedCommunityAdmin.getName());
        
        
        
        CbxCommunity.setSelectedItem(selectedCommunityAdmin.getCommunity());
        txtName.setText(selectedCommunityAdmin.getName());
        
        txtAddress.setText("");
        txtAddress.setText(selectedCommunityAdmin.getAddress());
        txtPhoneNumber.setText("");
        txtPhoneNumber.setText(String.valueOf(selectedCommunityAdmin.getPhoneNumber()));
        txtAge.setText(String.valueOf(selectedCommunityAdmin.getAge()));
        CbxGender.setSelectedItem(selectedCommunityAdmin.getGender());
        CbxCity.setSelectedItem(selectedCommunityAdmin.getCity());
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = tblRestaurants.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblRestaurants.getModel();
        CommunityAdmin selectedCommunityAdmin = (CommunityAdmin)model.getValueAt(selectedRowIndex, 0);
        // First delete the customer from employee
        
        // And then delete the userAccount
        this.system.getUserAccountDirectory().deleteUserAccount(
                this.system.getCommunityAdminDirectory().returnCommunityAdminDetails().
                        get(selectedRowIndex).returnUserAccount()
        );
        // finally delete the user from customer directory
        this.system.getCommunityAdminDirectory().deleteCommunityAdmin(selectedCommunityAdmin);
        
        JOptionPane.showMessageDialog(this, "Deleted the restaurant Successfully");

        this.populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void CbxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxCity;
    private javax.swing.JComboBox<String> CbxCommunity;
    private javax.swing.JComboBox<String> CbxGender;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPassword1;
    private javax.swing.JLabel lbPassword3;
    private javax.swing.JLabel lbRestaurant;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JTable tblRestaurants;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void populateTable(){
        System.out.println("Inside method to populate Community Admin details table");
        DefaultTableModel model = (DefaultTableModel) tblRestaurants.getModel();
        model.setRowCount(0);

        for(CommunityAdmin Cad : this.system.getCommunityAdminDirectory().returnCommunityAdminDetails()){
            System.out.println(Cad);
            Object[] row = new Object[8];
            row[0] = Cad;
            row[1] = Cad.getUserName();
            row[2] = Cad.getGender();
            row[3] = Cad.getAge();
            row[4] = Cad.getAddress();
            row[5] = Cad.getCity();
            row[6] = Cad.getCommunity();
            row[7] = Cad.getPhoneNumber();
            model.addRow(row);
        }
    }

}
