/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import javax.swing.JPanel;
import Business.CommunityAdmin.CommunityAdmin;
import Business.Customer.Customer;
import Business.Customer.Patients;
import Business.Customer.PatientsDirectory;
import Business.DeliveryMan.DeliveryMan;
import Business.Doctor.Doctor;
import Business.Restaurant.Restaurant;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Employee.Patient;
import Business.Encounter.Encounter;
import Business.Encounter.EncounterHistory;
import Business.Encounter.Vitalsigns;
import Business.HospitalAdmin.HospitalAdmin;
import Business.Restaurant.Restaurant;
import Business.Role.CommunityAdminRole;
import Business.Role.DoctorRole;
import Business.Role.HospitalAdminRole;
import Business.Role.PatientRole;
import Business.Role.SystemAdminRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author admin
 */
public class AddEncounterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddEncounter
     */
    
    JPanel userProcessContainer;
    EcoSystem system;
    private UserAccount userAccount;
    boolean check;
    PatientsDirectory patD;
    EncounterHistory encH;
    public AddEncounterJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
         this.patD = system.getPatientsDirectory();
         this.encH = system.getEncounterHistory();
        
        this.system = system;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CbxCommunity = new javax.swing.JComboBox<>();
        lblDOB = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox<>();
        lblCno = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        txtBpdi = new javax.swing.JTextField();
        lblBp1 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lbltempMetric = new javax.swing.JLabel();
        lblWtMetric = new javax.swing.JLabel();
        lblResMetric = new javax.swing.JLabel();
        lbltemp = new javax.swing.JLabel();
        txtTemp = new javax.swing.JTextField();
        lblWt = new javax.swing.JLabel();
        txtWt = new javax.swing.JTextField();
        lblBp = new javax.swing.JLabel();
        txtBpsys = new javax.swing.JTextField();
        lblResprate = new javax.swing.JLabel();
        txtResprate = new javax.swing.JTextField();
        lblEncounterTitle = new javax.swing.JLabel();
        lblVitals = new javax.swing.JLabel();
        lblPid = new javax.swing.JLabel();
        btnEncSubmit = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        lblPid1 = new javax.swing.JLabel();
        CbxCity = new javax.swing.JComboBox<>();
        lblCommunity1 = new javax.swing.JLabel();
        lblDOB1 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        btnGoBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CbxCommunity.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        CbxCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Mission Hill", "Jamaica Plain", "Huntington Avenue", "Bolyston" }));
        add(CbxCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 150, -1));

        lblDOB.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblDOB.setText("House Number : ");
        add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        lblGender.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblGender.setText("Gender:");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        cbGender.setBackground(new java.awt.Color(204, 204, 204));
        cbGender.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Female", "Male" }));
        add(cbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 150, -1));

        lblCno.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblCno.setText("Phone Number :");
        add(lblCno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        lblCommunity.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblCommunity.setText("Community:");
        add(lblCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        txtPhoneNumber.setEditable(false);
        txtPhoneNumber.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 200, -1));

        txtBpdi.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtBpdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 50, -1));

        lblBp1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblBp1.setText("/");
        add(lblBp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, -1));

        txtAddress.setEditable(false);
        txtAddress.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 200, -1));

        lbltempMetric.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lbltempMetric.setText("'F");
        add(lbltempMetric, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        lblWtMetric.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblWtMetric.setText("kgs");
        add(lblWtMetric, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        lblResMetric.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblResMetric.setText("bpm");
        add(lblResMetric, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, -1, -1));

        lbltemp.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lbltemp.setText("Temparature:");
        add(lbltemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        txtTemp.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 75, -1));

        lblWt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblWt.setText("Weight:");
        add(lblWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        txtWt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 75, -1));

        lblBp.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblBp.setText("Blood Pressure:");
        add(lblBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        txtBpsys.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtBpsys, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 50, -1));

        lblResprate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblResprate.setText("Respiration Rate:");
        add(lblResprate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, -1, -1));

        txtResprate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtResprate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 75, -1));

        lblEncounterTitle.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblEncounterTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncounterTitle.setText("Add a New Encounter");
        add(lblEncounterTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 771, 45));

        lblVitals.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblVitals.setText("    Vitals Information");
        add(lblVitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        lblPid.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblPid.setText("Person Name :");
        add(lblPid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        btnEncSubmit.setText("Submit");
        btnEncSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncSubmitActionPerformed(evt);
            }
        });
        add(btnEncSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, -1, -1));

        txtName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNameMouseExited(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 200, -1));

        txtUsername.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUsernameMouseExited(evt);
            }
        });
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 200, -1));

        lblPid1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblPid1.setText("Username :");
        add(lblPid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        CbxCity.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        CbxCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Boston", "New York" }));
        add(CbxCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 149, -1));

        lblCommunity1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblCommunity1.setText("City");
        add(lblCommunity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        lblDOB1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblDOB1.setText("Age :");
        add(lblDOB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        txtAge.setEditable(false);
        txtAge.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 200, -1));

        btnGoBack.setText("Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncSubmitActionPerformed
        // TODO add your handling code here:
        
        check=false;
       
        Vitalsigns vs=new Vitalsigns();
        int Age=Integer.parseInt(txtAge.getText());
        Double temp=Double.valueOf(txtTemp.getText());
        Double wt=Double.valueOf(txtWt.getText());
        Double BpS=Double.valueOf(txtBpsys.getText());
        Double BpD=Double.valueOf(txtBpdi.getText());
        Double Resp=Double.valueOf(txtResprate.getText());
        String Gender=String.valueOf(cbGender.getSelectedItem());
        PatientsDirectory usersList = this.system.getPatientsDirectory();
        String userName = (txtName.getText());
       ArrayList<Patients> pats = usersList.returnPatientsDetails();
        for(Patients pa : pats)
        {
            if(pa.getUserName().equals(userName)){
                
        
        pa.setAge(Age);
        pa.setGender(Gender);
//        Community com=new Community();
        
        pa.setAbTemp(CheckTemp(Age,temp));
        pa.setAbWt(CheckWt(Age,wt,Gender));
        pa.setAbBP(CheckBp(Age,BpS,BpD));
        pa.setAbResp(CheckResp(Age,Resp));
        pa.setVisitCount(pa.getVisitCount()+1);
        JOptionPane.showMessageDialog(this,"Patient visit details have been updated successfully!");
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss"); 
        LocalDateTime now = LocalDateTime.now(); 
        pa.setLastVisit(dtf.format(now));
        vs.setTemp(temp);
        vs.setWeight(wt);
        vs.setBPsys(BpS);
        vs.setBPdi(BpD);
        vs.setResprate(Resp);
//        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
//        LocalDateTime now = LocalDateTime.now();
        Encounter e = new Encounter();
        
        e.setPt(pa);
        e.setVs(vs);
        e.setVisitDate(dtf.format(now));
        System.out.println(e);
        encH.addNewEncounter(e);
        System.out.println(e);
//        lblTime.setText(dtf.format(now));
//        for(Patient p:patD.getPtList()){
//            if(Integer.parseInt(txtPName.getText())==p.getPid()){
//                VisitCnt=p.getVisitCount()+1;
//                JOptionPane.showMessageDialog(this,"Patient visit details have been updated successfully!");
//                p.setVisitCount(VisitCnt);
//                p.setLastVisit(dtf.format(now));
//                p.setAbTemp(pt.isAbTemp());
//                check=true;
//            }
//        }
        if(check){
//            VisitCnt++;
//            Patient pat=patD.addNewPatient();
//            pat.setPid(pt.getPid());
//            pat.setPName(pt.getPName());
//            pat.setDOB(pt.getDOB());
//            pat.setAge(pt.getAge());
//            pat.setGender(pt.getGender());
//            pat.setCom(pt.getCom());
//            pat.setContactNo(pt.getContactNo());
//            pat.setVisitCount(VisitCnt);
//            pat.setLastVisit(dtf.format(now));
//            pat.setAbTemp(pt.isAbTemp());
//            pat.setAbWt(pt.isAbWt());
//            pat.setAbBP(pt.isAbBP());
//            pat.setAbResp(pt.isAbResp());
            JOptionPane.showMessageDialog(this,"There is no person with this user name!");
        }

        txtName.setText("");
        txtName.setText("");
        txtAddress.setText("");
        txtAge.setText("");
        cbGender.setSelectedIndex(0);
        CbxCommunity.setSelectedIndex(0);
        CbxCity.setSelectedIndex(0);
        txtAddress.setText("");
        txtPhoneNumber.setText("");
        txtTemp.setText("");
        txtWt.setText("");
        txtBpsys.setText("");
        txtBpdi.setText("");
        txtResprate.setText("");
    }//GEN-LAST:event_btnEncSubmitActionPerformed
        }
    }
    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameMouseExited

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUsernameMouseExited

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        // TODO add your handling code here:
        int chkpid=0;
        if(evt.getKeyChar() == java.awt.event.KeyEvent.VK_TAB || evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER){
            for(Patients p : patD.returnPatientsDetails()){
                if(p.getUserName() == null ? txtUsername.getText() == null : p.getUserName().equals(txtUsername.getText())){
                    txtName.setText(p.getName());
                    txtAddress.setText(p.getAddress());
                    txtAge.setText(String.valueOf(p.getAge()));
                    cbGender.setSelectedItem(p.getGender());
                    CbxCommunity.setSelectedItem(p.getCommunity());
                    CbxCity.setSelectedItem(p.getCity());
                    
                    txtPhoneNumber.setText(p.getPhoneNumber());
                    chkpid++;
                }
            }
            if(chkpid==0){
                txtName.setText("");
                txtAddress.setText("");
                txtAge.setText("");
                cbGender.setSelectedIndex(0);
                CbxCommunity.setSelectedIndex(0);
                CbxCity.setSelectedIndex(0);
                txtAddress.setText("");
                txtPhoneNumber.setText("");
                JOptionPane.showMessageDialog(this,"This Id does not exist in Person Directory.Please add the person.");
            }
        }
        else{
//            JOptionPane.showMessageDialog(this,"Please enter patient id.");
        }
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        Component[] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof DoctorWorkAreaJPanel){
                DoctorWorkAreaJPanel doctorWorkAreaJPanel= (DoctorWorkAreaJPanel) comp;
                doctorWorkAreaJPanel.populateTree();
            }
        }
    }//GEN-LAST:event_btnGoBackActionPerformed

 private boolean CheckTemp(int Age, Double temp) {
        boolean res=false;
        
        if(Age>12 && (temp>100.0 || temp <95.0)) res=true;
        else if((Age<=12 && Age >3)&& (temp>99.0 || temp <95.0)) res=true;
        else if(Age<=3 && (temp>100.4 || temp <95.0)) res=true;
        return res;
    }

    private boolean CheckWt(int Age, Double wt, String Gender) {
        boolean res=false;
        if(Age<3){
            if(wt>26) res=true;
        }
        if(Age>2 && Age<13){
            if(Gender=="Female" && (wt<26 || wt>90) ) res=true;
            else if(Gender!="Female" && (wt<27 || wt>89) ) res=true;
        }
        if(Age>12 && Age<26){
            if(Gender=="Female" && (wt<90 || wt>130) ) res=true;
            else if(Gender!="Female" && (wt<90 || wt>158) ) res=true;
        }
        if(Age>25){
            if(Gender=="Female" && wt>155 ) res=true;
            else if(Gender!="Female" && wt>180 ) res=true;
        }
        return res;
    }

    private boolean CheckBp(int Age, Double Bps, Double Bpd) {
        boolean res=false;
        if(Age<=2){
            if((Bps<83 || Bps>117) && (Bpd<38 || Bpd>76)) res=true;
        }
        if(Age>=3 && Age<=8){
            if((Bps<=101 || Bps>=106) && (Bpd<=61 || Bpd>=71)) res=true;
        }
        if(Age<=9 && Age>=14){
            if((Bps<=110 || Bps>=120) && (Bpd<=72 || Bpd>=77)) res=true;
        }
        if(Age>=15 && Age<=20){
            if((Bps<115 || Bps>120) && (Bpd<78 || Bpd>80)) res=true;
        }
        if(Age>20 && Age<31){
            if((Bps<119 || Bps>122) && (Bpd<79 || Bpd>=80)) res=true;
        }
        if(Age>30 && Age<40){
            if((Bps<120 || Bps>123) && (Bpd<80 || Bpd>83)) res=true;
        }
        if(Age>=40 && Age<50){
            if((Bps<123 || Bps>126) && (Bpd<83 || Bpd>84)) res=true;
        }
        if(Age>=50 && Age<=60){
            if((Bps<128 || Bps>130) && (Bpd<84 || Bpd>85)) res=true;
        }
        if(Age>60){
            if((Bps<129 || Bps>135) && (Bpd<85 || Bpd>88)) res=true;
        }
        return res;
    }

    private boolean CheckResp(int Age, Double Resp) {
        boolean res=false;
        if(Age<2){
            if(Resp<30 || Resp>60) res=true;
        }
        if(Age>=2 && Age<4){
            if(Resp<25 || Resp>=40) res=true;
        }
        if(Age>3 && Age<=6){
            if(Resp<23 || Resp>=34) res=true;
        }
        if(Age>6 && Age<=12){
            if(Resp<19 || Resp>=30) res=true;
        }
        if(Age>12 && Age<=18){
            if(Resp<13 || Resp>=20) res=true;
        }
        if(Age>18){
            if(Resp<12 || Resp>=16) res=true;
        }
        return res;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxCity;
    private javax.swing.JComboBox<String> CbxCommunity;
    private javax.swing.JButton btnEncSubmit;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JLabel lblBp;
    private javax.swing.JLabel lblBp1;
    private javax.swing.JLabel lblCno;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblCommunity1;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOB1;
    private javax.swing.JLabel lblEncounterTitle;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblPid;
    private javax.swing.JLabel lblPid1;
    private javax.swing.JLabel lblResMetric;
    private javax.swing.JLabel lblResprate;
    private javax.swing.JLabel lblVitals;
    private javax.swing.JLabel lblWt;
    private javax.swing.JLabel lblWtMetric;
    private javax.swing.JLabel lbltemp;
    private javax.swing.JLabel lbltempMetric;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBpdi;
    private javax.swing.JTextField txtBpsys;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtResprate;
    private javax.swing.JTextField txtTemp;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtWt;
    // End of variables declaration//GEN-END:variables
}
