/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.DoctorRole;
import Business.CommunityAdmin.CommunityAdmin;
import Business.Customer.Customer;
import Business.Customer.Patients;
import Business.Customer.PatientsDirectory;
import Business.DeliveryMan.DeliveryMan;
import Business.Doctor.Doctor;
import Business.Restaurant.Restaurant;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Employee.Patient;
import Business.Encounter.Encounter;
import Business.Encounter.EncounterHistory;
import Business.Encounter.Vitalsigns;
import Business.HospitalAdmin.HospitalAdmin;
import Business.Restaurant.Restaurant;
import Business.Role.CommunityAdminRole;
import Business.Role.DoctorRole;
import Business.Role.HospitalAdminRole;
import Business.Role.PatientRole;
import Business.Role.SystemAdminRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import userinterface.CommunityAdminRole.CommunityAdminWorkAreaJPanel;
/**
 *
 * @author rajanikshithkatta
 */
public class ViewEncounterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEncounterJPanel
     */
    
        JPanel userProcessContainer;
    EcoSystem system;
    private UserAccount userAccount;
    boolean check;
    PatientsDirectory patD;
    EncounterHistory encH;
    public ViewEncounterJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
                 this.userProcessContainer = userProcessContainer;
        this.patD = system.getPatientsDirectory();
         this.encH = system.getEncounterHistory();
        
        this.system = system;
        this.populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResprate = new javax.swing.JTextField();
        lblResprate = new javax.swing.JLabel();
        lblBp = new javax.swing.JLabel();
        txtWt = new javax.swing.JTextField();
        lblWt = new javax.swing.JLabel();
        txtTemp = new javax.swing.JTextField();
        lbltemp = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtHNo = new javax.swing.JTextField();
        lblHno = new javax.swing.JLabel();
        cbCommunity = new javax.swing.JComboBox<>();
        lblResMetric = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        lblWtMetric = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lbltempMetric = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCno = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblCno = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox<>();
        lblGender = new javax.swing.JLabel();
        txtBpdi = new javax.swing.JTextField();
        lblBp1 = new javax.swing.JLabel();
        txtPName = new javax.swing.JTextField();
        lblPersonName = new javax.swing.JLabel();
        txtBpsys = new javax.swing.JTextField();
        txtVisitDt = new javax.swing.JTextField();
        lblVisitDate = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEncounter = new javax.swing.JTable();
        lblViewEncounterTitle = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResprate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtResprate, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 502, 75, -1));

        lblResprate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblResprate.setText("Respiration Rate:");
        add(lblResprate, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 505, -1, -1));

        lblBp.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblBp.setText("Blood Pressure:");
        add(lblBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 476, -1, -1));

        txtWt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 438, 75, -1));

        lblWt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblWt.setText("Weight:");
        add(lblWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 438, -1, -1));

        txtTemp.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 403, 75, -1));

        lbltemp.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lbltemp.setText("Temparature:");
        add(lbltemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 403, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 566, -1, -1));

        txtHNo.setEditable(false);
        txtHNo.setBackground(new java.awt.Color(204, 204, 204));
        txtHNo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtHNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 345, 200, -1));

        lblHno.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblHno.setText("House No:");
        add(lblHno, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 348, -1, -1));

        cbCommunity.setBackground(new java.awt.Color(204, 204, 204));
        cbCommunity.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cbCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Mission Hill", "Jamaica Plain", "Huntington Avenue", "Bolyston" }));
        add(cbCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 316, 150, -1));

        lblResMetric.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblResMetric.setText("bpm");
        add(lblResMetric, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 505, -1, -1));

        lblCommunity.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblCommunity.setText("Community:");
        add(lblCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 319, -1, -1));

        lblWtMetric.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblWtMetric.setText("kgs");
        add(lblWtMetric, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 438, -1, -1));

        txtCity.setEditable(false);
        txtCity.setBackground(new java.awt.Color(204, 204, 204));
        txtCity.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 287, 200, -1));

        lbltempMetric.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lbltempMetric.setText("'F");
        add(lbltempMetric, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 406, -1, -1));

        lblCity.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblCity.setText("City:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 290, -1, -1));

        txtCno.setEditable(false);
        txtCno.setBackground(new java.awt.Color(204, 204, 204));
        txtCno.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtCno, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 374, 200, -1));

        txtAge.setEditable(false);
        txtAge.setBackground(new java.awt.Color(204, 204, 204));
        txtAge.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 223, 200, -1));

        lblCno.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblCno.setText("Contact Number:");
        add(lblCno, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 377, -1, -1));

        lblAge.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblAge.setText("Age:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 223, -1, -1));

        cbGender.setBackground(new java.awt.Color(204, 204, 204));
        cbGender.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Male", "Female" }));
        add(cbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 258, 150, -1));

        lblGender.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblGender.setText("Gender:");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 261, -1, -1));

        txtBpdi.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtBpdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 473, 50, -1));

        lblBp1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblBp1.setText("/");
        add(lblBp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 476, -1, -1));

        txtPName.setEditable(false);
        txtPName.setBackground(new java.awt.Color(204, 204, 204));
        txtPName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtPName, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 194, 200, -1));

        lblPersonName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblPersonName.setText("Name:");
        add(lblPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 197, -1, -1));

        txtBpsys.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtBpsys, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 473, 50, -1));

        txtVisitDt.setEditable(false);
        txtVisitDt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(txtVisitDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 531, 200, -1));

        lblVisitDate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblVisitDate.setText("Visit Date:");
        add(lblVisitDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 534, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(75, 30));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 158, 130, -1));

        btnView.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnView.setText("View/Edit");
        btnView.setPreferredSize(new java.awt.Dimension(75, 30));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 157, 130, -1));

        tblEncounter.setBackground(new java.awt.Color(204, 204, 204));
        tblEncounter.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        tblEncounter.setForeground(new java.awt.Color(51, 0, 0));
        tblEncounter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "City", "Community Name", "Address", "Phone Number", "Temperature", "Weight", "BP", "Respiration rate", "Visit Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEncounter.setPreferredSize(new java.awt.Dimension(1000, 128));
        jScrollPane1.setViewportView(tblEncounter);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, 1220, 99));

        lblViewEncounterTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblViewEncounterTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewEncounterTitle.setText("View/Modify Encounter Details");
        add(lblViewEncounterTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 0, 860, 40));

        btnGoBack.setText("Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblEncounter.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a record to update.");
            return;
        }

        DefaultTableModel MediCare = (DefaultTableModel) tblEncounter.getModel();
        Encounter selectedEnc = (Encounter) MediCare.getValueAt(selectedRowIndex, 0);
//        Patient pt=new Patient();
//        pt.setPid(Integer.parseInt(txtId.getText()));
//        pt.setPName(txtPName.getText());
//        pt.setDOB(txtDOB.getText());
//        pt.setAge(Integer.parseInt(txtAge.getText()));
//        pt.setGender(String.valueOf(cbGender.getSelectedItem()));
//        Community com=new Community();
//        com.setComId(cbCommunity.getSelectedIndex());
//        com.setCommunityName(String.valueOf(cbCommunity.getSelectedItem()));
//        com.setCity(txtCity.getText());
//        com.setHouseNo(Integer.parseInt(txtHNo.getText()));
//        pt.setCom(com);
//        pt.setContactNo(Long.parseLong(txtCno.getText()));
        Vitalsigns vs=new Vitalsigns();
        vs.setTemp(Double.parseDouble(txtTemp.getText()));
        vs.setWeight(Double.parseDouble(txtWt.getText()));
        vs.setBPsys(Double.parseDouble(txtBpsys.getText()));
        vs.setBPdi(Double.parseDouble(txtBpdi.getText()));
        vs.setResprate(Double.parseDouble(txtResprate.getText()));
        PatientsDirectory usersList = this.system.getPatientsDirectory();
        String userName = (txtPName.getText());
       ArrayList<Patients> pats = usersList.returnPatientsDetails();
         for(Patients pa : pats)
        {
            if(pa.getUserName().equals(userName)){
                selectedEnc.setPt(pa);
                break;
            }
      
        selectedEnc.setVs(vs);
        txtPName.setText(selectedEnc.getPt().getName());
//        txtDOB.setText(selectedEnc.getPt().getDOB());
        cbGender.setSelectedItem(selectedEnc.getPt().getGender());
        txtAge.setText(String.valueOf(selectedEnc.getPt().getAge()));
        cbCommunity.setSelectedItem(selectedEnc.getPt().getCommunity());
        txtCity.setText(selectedEnc.getPt().getCity());
        txtHNo.setText(String.valueOf(selectedEnc.getPt().getAddress()));
        txtCno.setText(String.valueOf(selectedEnc.getPt().getPhoneNumber()));
        txtTemp.setText(String.valueOf(selectedEnc.getVs().getTemp()));
        txtWt.setText(String.valueOf(selectedEnc.getVs().getWeight()));
        txtBpsys.setText(String.valueOf(selectedEnc.getVs().getBPsys()));
        txtBpdi.setText(String.valueOf(selectedEnc.getVs().getBPdi()));
        txtResprate.setText(String.valueOf(selectedEnc.getVs().getResprate()));
        JOptionPane.showMessageDialog(this,"Encounter details have been updated successfully!");
        populateTable();

       
        txtPName.setText("");
//        txtDOB.setText("");
        txtAge.setText("");
        cbGender.setSelectedIndex(0);
        cbCommunity.setSelectedIndex(0);
        txtCity.setText("");
        txtHNo.setText("");
        txtCno.setText("");
        txtTemp.setText("");
        txtWt.setText("");
        txtBpsys.setText("");
        txtBpdi.setText("");
        txtResprate.setText("");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblEncounter.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a record to delete.");
            return;
        }

        DefaultTableModel MediCare = (DefaultTableModel) tblEncounter.getModel();
        Encounter selectedEnc = (Encounter) MediCare.getValueAt(selectedRowIndex, 0);
        for(Encounter E: encH.getEList()){
            if(E==selectedEnc){
                E.getPt().setVisitCount((E.getPt().getVisitCount())-1);
                encH.deleteCab(selectedEnc);
                JOptionPane.showMessageDialog(this,"The selected record has been deleted successfully.");
            }
        }
        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblEncounter.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a record to view.");
            return;
        }

        DefaultTableModel MediCare = (DefaultTableModel) tblEncounter.getModel();
        Encounter selectedEnc = (Encounter) MediCare.getValueAt(selectedRowIndex, 0);

//        txtId.setText(String.valueOf(selectedEnc.getPt().getPid()));
        txtPName.setText(selectedEnc.getPt().getName());
//        txtDOB.setText(selectedEnc.getPt().getDOB());
        txtAge.setText(String.valueOf(selectedEnc.getPt().getAge()));
        cbGender.setSelectedItem(selectedEnc.getPt().getGender());
        cbCommunity.setSelectedItem(selectedEnc.getPt().getCommunity());
        txtCity.setText(selectedEnc.getPt().getCity());
        txtHNo.setText(String.valueOf(selectedEnc.getPt().getAddress()));
        txtCno.setText(String.valueOf(selectedEnc.getPt().getPhoneNumber()));
        txtTemp.setText(String.valueOf(selectedEnc.getVs().getTemp()));
        txtWt.setText(String.valueOf(selectedEnc.getVs().getWeight()));
        txtBpsys.setText(String.valueOf(selectedEnc.getVs().getBPsys()));
        txtBpdi.setText(String.valueOf(selectedEnc.getVs().getBPdi()));
        txtResprate.setText(String.valueOf(selectedEnc.getVs().getResprate()));
        txtVisitDt.setText(selectedEnc.getVisitDate());
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        Component[] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof DoctorWorkAreaJPanel){
                DoctorWorkAreaJPanel doctorWorkAreaJPanel= (DoctorWorkAreaJPanel) comp;
                doctorWorkAreaJPanel.populateTree();
            }
        }
    }//GEN-LAST:event_btnGoBackActionPerformed

private void populateTable() {
        DefaultTableModel MediCare = (DefaultTableModel) tblEncounter.getModel();
        MediCare.setRowCount(0);   
        for(Encounter e : encH.getEList()){
            Object[] row = new Object[12];  
            row[0] =  e;
            row[1] = e.getPt().getAge();
            row[2] = e.getPt().getGender();
            row[3] = e.getPt().getCity();
            row[4] = e.getPt().getCommunity();
            row[5] = e.getPt().getAddress();
            row[6] = e.getPt().getPhoneNumber(); 
            row[7] = e.getVs().getTemp();
            row[8] = e.getVs().getWeight();
            row[9] = e.getVs().getBPsys()+" / "+e.getVs().getBPdi();
            row[10] = e.getVs().getResprate();
            row[11] = e.getVisitDate();
            MediCare.addRow(row);    
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cbCommunity;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBp;
    private javax.swing.JLabel lblBp1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCno;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHno;
    private javax.swing.JLabel lblPersonName;
    private javax.swing.JLabel lblResMetric;
    private javax.swing.JLabel lblResprate;
    private javax.swing.JLabel lblViewEncounterTitle;
    private javax.swing.JLabel lblVisitDate;
    private javax.swing.JLabel lblWt;
    private javax.swing.JLabel lblWtMetric;
    private javax.swing.JLabel lbltemp;
    private javax.swing.JLabel lbltempMetric;
    private javax.swing.JTable tblEncounter;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBpdi;
    private javax.swing.JTextField txtBpsys;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCno;
    private javax.swing.JTextField txtHNo;
    private javax.swing.JTextField txtPName;
    private javax.swing.JTextField txtResprate;
    private javax.swing.JTextField txtTemp;
    private javax.swing.JTextField txtVisitDt;
    private javax.swing.JTextField txtWt;
    // End of variables declaration//GEN-END:variables
}
