

package userinterface.CommunityAdminRole;


import Business.CommunityAdmin.CommunityAdmin;
import Business.CommunityAdmin.CommunityAdminDirectory;
import Business.EcoSystem;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  admin
 */
public class CommunityAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount ua;
    CommunityAdmin cad;
    CommunityAdminDirectory communityAdminDirectory;
    
    /** Creates new form AdminWorkAreaJPanel */
    public CommunityAdminWorkAreaJPanel(JPanel userProcessContainer,
                            UserAccount ua ,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ua = ua;
        this.system = system;
        //valueLabel.setText();
        communityAdminDirectory = system.getCommunityAdminDirectory();
        this.cad = communityAdminDirectory.getCommunityAdmins(ua.getUsername());
        lbUserName.setText(this.cad.getName());
        populateTree();
    }
    
    public void populateTree(){
//        DefaultTreeModel model=(DefaultTreeModel)jTree.getModel();
       // Add the code for draw your system structure shown by JTree
       
//        model.reload();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddPerson = new javax.swing.JButton();
        btnManagePerson = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddPerson.setText("Add Person");
        btnAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonActionPerformed(evt);
            }
        });
        add(btnAddPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 160, -1));

        btnManagePerson.setText("Manage Person");
        btnManagePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePersonActionPerformed(evt);
            }
        });
        add(btnManagePerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 160, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Welcome : ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        lbUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbUserName.setText("<value>");
        add(lbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonActionPerformed
        // TODO add your handling code here:
        AddPerson addPersonObj = new AddPerson(userProcessContainer,
            system);
        userProcessContainer.add("AddPerson", addPersonObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddPersonActionPerformed

    private void btnManagePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePersonActionPerformed
        // TODO add your handling code here:
        ManagePersonDetails PersonDetailsObj = new ManagePersonDetails(
            userProcessContainer, system);

        userProcessContainer.add("PersonDashboard", PersonDetailsObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePersonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPerson;
    private javax.swing.JButton btnManagePerson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbUserName;
    // End of variables declaration//GEN-END:variables
    
}
