/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Hospital.PatientsDirectory;
import Business.EcoSystem;
import Business.Encounter.EncounterHistory;


import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private EncounterHistory encH;
    private PatientsDirectory patD;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
//        this.encH = encH;
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.system = system;
        lbUserName.setText(account.getUsername());
        this.patD = system.getPatientsDirectory();
        populateTree();
    }
    public void populateTree(){
//        DefaultTreeModel model=(DefaultTreeModel)jTree.getModel();
       // Add the code for draw your system structure shown by JTree
       
//        model.reload();
    }
    
    public void populateTable(){
//        System.out.println("Inside method to populate orders table");
//        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
//        model.setRowCount(0);
//        
//        for(Order o : this.system.getOrderDirectory().getOrderDirectory()){
//            System.out.println(this.userAccount.getUsername());
//            System.out.println(o.getDeliveryMan());
//            if((this.userAccount.getUsername().equals(o.getDeliveryMan()))
//                    && (o.getOrderStatus().equals("Delivery Assigned") ||
//                           o.getOrderStatus().equals("Order Picked up") ||
//                    o.getOrderStatus().equals("Delivered"))){
//                System.out.println(o);
//                Object[] row = new Object[5];
//                row[0] = o;
//                row[1] = o.getSender().getUsername();
//                row[2] = o.getReceiver().getUsername();
//                row[3] = o.getOrderStatus();
//                row[4] = o.getMessage();
//                model.addRow(row);
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        btnViewEncounter = new javax.swing.JButton();
        btnAddEncounter = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Welcome : ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        lbUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbUserName.setText("<value>");
        add(lbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 120, -1));

        btnViewEncounter.setText("View Encounter");
        btnViewEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEncounterActionPerformed(evt);
            }
        });
        add(btnViewEncounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        btnAddEncounter.setText("Add Encounter");
        btnAddEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEncounterActionPerformed(evt);
            }
        });
        add(btnAddEncounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEncounterActionPerformed
        // TODO add your handling code here:
        ViewEncounterJPanel viewEncounterObj = new ViewEncounterJPanel(userProcessContainer,
            system);
        userProcessContainer.add("ViewEncounter", viewEncounterObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewEncounterActionPerformed

    private void btnAddEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEncounterActionPerformed
        // TODO add your handling code here:
        AddEncounterJPanel addEncounterObj = new AddEncounterJPanel(userProcessContainer,
            system);
        userProcessContainer.add("AddEncounter", addEncounterObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddEncounterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEncounter;
    private javax.swing.JButton btnViewEncounter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbUserName;
    // End of variables declaration//GEN-END:variables

}
