/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.HospitalAdminRole;

import Business.EcoSystem;
import Business.HospitalAdmin.HospitalAdmin;
import Business.HospitalAdmin.HospitalAdminDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class HospitalAdminWorkAreaNewJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private HospitalAdmin H;
    private HospitalAdminDirectory Had;
    /**
     * Creates new form HospitalAdminWorkAreaNew
     */
    public HospitalAdminWorkAreaNewJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
                
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.system = system;
        populateTree();
        Had = system.getHospitalAdminDirectory();
        this.H = Had.getHospitalAdmins(userAccount.getUsername());
        valueLabel1.setText(this.H.getName());
        
    }
    
    public void populateTree(){
//        DefaultTreeModel model=(DefaultTreeModel)jTree.getModel();
       // Add the code for draw your system structure shown by JTree
       
//        model.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        btnNewDoctor = new javax.swing.JButton();
        btnManageDoctors = new javax.swing.JButton();
        valueLabel1 = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setText("<value>");

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Welcome ");

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNewDoctor.setText("Add Doctor");
        btnNewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDoctorActionPerformed(evt);
            }
        });
        add(btnNewDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 90, 198, -1));

        btnManageDoctors.setText("Manage Doctors");
        btnManageDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDoctorsActionPerformed(evt);
            }
        });
        add(btnManageDoctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 131, 198, -1));

        valueLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel1.setText("<value>");
        add(valueLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 33, 158, 26));

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Welcome ");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 31, 99, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDoctorActionPerformed
        // TODO add your handling code here:
        AddDoctor addDoctorObj = new AddDoctor(userProcessContainer,
            system);
        userProcessContainer.add("AddDoctor", addDoctorObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNewDoctorActionPerformed

    private void btnManageDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDoctorsActionPerformed
        // TODO add your handling code here:
        ManageDoctors DoctorsDetailsObj = new ManageDoctors(
            userProcessContainer, system);

        userProcessContainer.add("DoctorDashboard", DoctorsDetailsObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDoctorsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDoctors;
    private javax.swing.JButton btnNewDoctor;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel valueLabel1;
    // End of variables declaration//GEN-END:variables
}
