/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Employee.Profile;
import Employee.ProfileHistory;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    ProfileHistory history;
    public int check=0;
    private final JFileChooser PhotoFileChooser;
    
    public CreateJPanel(ProfileHistory history) {
        initComponents();
        this.history = history;
        PhotoFileChooser = new JFileChooser();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtTeamInfo = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtPhoto = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTeamInfo = new javax.swing.JLabel();
        lblContactInfo = new javax.swing.JLabel();
        lblPositionTitle = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        txtPositionTitle = new javax.swing.JTextField();
        btnPhoto = new javax.swing.JButton();
        lblStartDateErr = new javax.swing.JLabel();
        lblGenderErr = new javax.swing.JLabel();
        lblLevelErr = new javax.swing.JLabel();
        lblPositionTitleErr = new javax.swing.JLabel();
        lblTeamInfoErr = new javax.swing.JLabel();
        lblPhoneNumberErr = new javax.swing.JLabel();
        lblEmailAddressErr = new javax.swing.JLabel();
        lblPhotoErr = new javax.swing.JLabel();
        drpdwnGender = new javax.swing.JComboBox<>();
        lblNameErr = new javax.swing.JLabel();
        lblEIDErr = new javax.swing.JLabel();
        lblAgeErr = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Employee Profile");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 18, -1, -1));

        txtTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeamInfoActionPerformed(evt);
            }
        });
        add(txtTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 231, 253, -1));

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 317, 253, -1));

        txtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddressActionPerformed(evt);
            }
        });
        add(txtEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 352, 253, -1));

        lblName.setText("Employee Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 57, -1, 22));

        txtPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhotoActionPerformed(evt);
            }
        });
        add(txtPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 381, 0, -1));

        lblID.setText("Employee ID:");
        add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 86, -1, 22));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 520, -1, -1));

        lblAge.setText("Age:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 115, -1, 22));

        lblGender.setText("Gender:");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 144, -1, 22));

        lblLevel.setText("Level:");
        add(lblLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 202, -1, 22));

        lblDate.setText("Start Date:");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 173, -1, 22));

        lblTeamInfo.setText("Team Info:");
        add(lblTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 231, -1, 22));

        lblContactInfo.setText("Contact Info:");
        add(lblContactInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 289, -1, 22));

        lblPositionTitle.setText("Position Title:");
        add(lblPositionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 260, -1, 22));

        lblPhoneNumber.setText("Cell Phone Number:");
        add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 317, -1, 22));

        lblEmailAddress.setText("Email Address:");
        add(lblEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 352, -1, 22));

        lblPhoto.setText("Photo:");
        add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 381, -1, 22));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 57, 253, -1));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 115, 253, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 86, 253, -1));

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 173, 253, -1));

        txtLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLevelActionPerformed(evt);
            }
        });
        add(txtLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 202, 253, -1));

        txtPositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPositionTitleActionPerformed(evt);
            }
        });
        add(txtPositionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 253, -1));

        btnPhoto.setText("Select Photo");
        btnPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhotoActionPerformed(evt);
            }
        });
        add(btnPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        lblStartDateErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblStartDateErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, 18));

        lblGenderErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblGenderErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 148, -1, 20));

        lblLevelErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblLevelErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, 24));

        lblPositionTitleErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblPositionTitleErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, 18));

        lblTeamInfoErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblTeamInfoErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, 18));

        lblPhoneNumberErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblPhoneNumberErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, 18));

        lblEmailAddressErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblEmailAddressErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, 18));
        add(lblPhotoErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        drpdwnGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Other" }));
        drpdwnGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpdwnGenderActionPerformed(evt);
            }
        });
        add(drpdwnGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 30));
        add(lblNameErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));
        add(lblEIDErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));
        add(lblAgeErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeamInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeamInfoActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddressActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        check=0;
        String Name="";
        int EmployeeID=0;
        int Age=0;
        String Gender="";
        String StartDate="";
        String Level="";
        String TeamInfo="";
        String PositionTitle="";
        long PhoneNumber=0;
        String EmailAddress="";
        String Photo="";
        if(txtName.getText().length()==0){
            lblNameErr.setText("Please enter the employee name");
        }
        else{
            Name = txtName.getText();
            lblNameErr.setText("");
            check++;
        }
        if(txtID.getText().length()==0){
            lblEIDErr.setText("Please enter the employee ID");
        }
        else{
            EmployeeID = Integer.parseInt(txtID.getText());
            lblEIDErr.setText("");
            check++;
        }
        if(txtAge.getText().length()==0){
            lblAgeErr.setText("Please enter the employee age");
        }
        else{
            Age = Integer.parseInt(txtAge.getText());
            lblAgeErr.setText("");
            check++;
        }
        if(drpdwnGender.getSelectedItem()=="Select"){
           lblGenderErr.setText("Please select the gender");           
       }
       else{
            Gender = String.valueOf(drpdwnGender.getSelectedItem());
            lblGenderErr.setText("");
            check++;
        }
        if(txtDate.getText().length()==0){
            lblStartDateErr.setText("Please enter the employee start date");
        }
        else{
            StartDate = txtDate.getText();
            lblStartDateErr.setText("");
            check++;
        }
        if(txtLevel.getText().length()==0){
            lblLevelErr.setText("Please enter the employee level");
        }
        else{
            Level = txtLevel.getText();
            lblLevelErr.setText("");
            check++;
        }
        if(txtTeamInfo.getText().length()==0){
            lblTeamInfoErr.setText("Please enter the employee team info");
        }
        else{
            TeamInfo = txtTeamInfo.getText();
            lblTeamInfoErr.setText("");
            check++;
        }
        if(txtPositionTitle.getText().length()==0){
            lblPositionTitleErr.setText("Please enter the employee position title");
        }
        else{
            PositionTitle = txtPositionTitle.getText();
            lblPositionTitleErr.setText("");
            check++;
        }
        if(txtPhoneNumber.getText().length()==0){
            lblPhoneNumberErr.setText("Please enter the employee phone number");
        }
        else{
            PhoneNumber = Long.parseLong(txtPhoneNumber.getText());
            lblPhoneNumberErr.setText("");
            check++;
        }
        if(txtEmailAddress.getText().length()==0){
            lblEmailAddressErr.setText("Please enter the employee email ID");
        }
        else{
            EmailAddress = txtEmailAddress.getText();
            lblEmailAddressErr.setText("");
            check++;
        }
        if(txtPhoto.getText().length()==0){
            lblPhotoErr.setText("Please select the employee photo");
        }
        else{
            Photo = txtPhoto.getText();
            lblPhotoErr.setText("");
            check++;
        }
       
        if(check==11){Profile pro = history.addNewProfile();
        pro.setName(Name);
        pro.setEmployeeID(EmployeeID);
        pro.setAge(Age);
        pro.setGender(Gender);
        pro.setStartDate(StartDate);
        pro.setLevel(Level);
        pro.setTeamInfo(TeamInfo);
        pro.setPositionTitle(PositionTitle);
        pro.setPhoneNumber(PhoneNumber);
        pro.setEmailAddress(EmailAddress);
        pro.setPhoto(Photo);
        
        JOptionPane.showMessageDialog(this, "New Profile Added Successfully!");
            
        txtName.setText("");
        txtID.setText("");
        txtAge.setText("");
        drpdwnGender.setSelectedIndex(0);
        txtDate.setText("");
        txtLevel.setText("");
        txtTeamInfo.setText("");
        txtPositionTitle.setText("");
        txtPhoneNumber.setText("");
        txtEmailAddress.setText("");
        txtPhoto.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this,"Please enter the mandatory fields"); 
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLevelActionPerformed

    private void txtPositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionTitleActionPerformed

    private void txtPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhotoActionPerformed

    private void drpdwnGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpdwnGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpdwnGenderActionPerformed

    private void btnPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhotoActionPerformed
        // TODO add your handling code here:
        PhotoFileChooser.setCurrentDirectory(new File("/Users/admin/Documents/ProfilePics"));
        int Value = PhotoFileChooser.showOpenDialog(this);
        if(Value==JFileChooser.APPROVE_OPTION){
            txtPhoto.setText( PhotoFileChooser.getSelectedFile().toString());

        }
        else{
            txtPhoto.setText("No File Selected");
        }
    }//GEN-LAST:event_btnPhotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPhoto;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> drpdwnGender;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAgeErr;
    private javax.swing.JLabel lblContactInfo;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEIDErr;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEmailAddressErr;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGenderErr;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblLevelErr;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameErr;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumberErr;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPhotoErr;
    private javax.swing.JLabel lblPositionTitle;
    private javax.swing.JLabel lblPositionTitleErr;
    private javax.swing.JLabel lblStartDateErr;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JLabel lblTeamInfoErr;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPhoto;
    private javax.swing.JTextField txtPositionTitle;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables
}
