/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Employee.Profile;
import Employee.ProfileHistory;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    ProfileHistory history;
    public int check=0;
    private final JFileChooser PhotoFileChooser;
    
    public CreateJPanel(ProfileHistory history) {
        initComponents();
        this.history = history;
                PhotoFileChooser = new JFileChooser();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtTeamInfo = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtPhoto = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTeamInfo = new javax.swing.JLabel();
        lblContactInfo = new javax.swing.JLabel();
        lblPositionTitle = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        txtPositionTitle = new javax.swing.JTextField();
        lblNameErr = new javax.swing.JLabel();
        btnPhoto = new javax.swing.JButton();
        lblEIDErr = new javax.swing.JLabel();
        lblAgeErr = new javax.swing.JLabel();
        lblStartDateErr = new javax.swing.JLabel();
        lblGenderErr = new javax.swing.JLabel();
        lblLevelErr = new javax.swing.JLabel();
        lblPositionTitleErr = new javax.swing.JLabel();
        lblTeamInfoErr = new javax.swing.JLabel();
        lblPhoneNumberErr = new javax.swing.JLabel();
        lblEmailAddressErr = new javax.swing.JLabel();
        lblPhotoErr = new javax.swing.JLabel();
        drpdwnGender = new javax.swing.JComboBox<>();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Profile");

        txtTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeamInfoActionPerformed(evt);
            }
        });

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        txtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddressActionPerformed(evt);
            }
        });

        lblName.setText("Employee Name:");

        txtPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhotoActionPerformed(evt);
            }
        });

        lblID.setText("Employee ID:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblAge.setText("Age:");

        lblGender.setText("Gender:");

        lblLevel.setText("Level:");

        lblDate.setText("Start Date:");

        lblTeamInfo.setText("Team Info:");

        lblContactInfo.setText("Contact Info:");

        lblPositionTitle.setText("Position Title:");

        lblPhoneNumber.setText("Cell Phone Number:");

        lblEmailAddress.setText("Email Address:");

        lblPhoto.setText("Photo:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        txtLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLevelActionPerformed(evt);
            }
        });

        txtPositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPositionTitleActionPerformed(evt);
            }
        });

        lblNameErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnPhoto.setText("Select Photo");
        btnPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhotoActionPerformed(evt);
            }
        });

        lblEIDErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblAgeErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblStartDateErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblGenderErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblLevelErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblPositionTitleErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTeamInfoErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblPhoneNumberErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblEmailAddressErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        drpdwnGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Other" }));
        drpdwnGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpdwnGenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEIDErr, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNameErr, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPhoto)
                            .addComponent(drpdwnGender, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhotoErr)
                            .addComponent(lblGenderErr)
                            .addComponent(lblPositionTitleErr)
                            .addComponent(lblTeamInfoErr)
                            .addComponent(lblLevelErr)
                            .addComponent(lblStartDateErr)
                            .addComponent(lblAgeErr)
                            .addComponent(lblPhoneNumberErr)
                            .addComponent(lblEmailAddressErr))))
                .addContainerGap(632, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPhoto)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPhoneNumber)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblName)
                                        .addComponent(lblID, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblGender, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblLevel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTeamInfo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblPositionTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblContactInfo, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(6, 6, 6)))
                        .addComponent(lblEmailAddress, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEmailAddress)
                        .addComponent(txtPhoneNumber)
                        .addComponent(txtPositionTitle)
                        .addComponent(txtTeamInfo)
                        .addComponent(txtLevel)
                        .addComponent(txtName)
                        .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                        .addComponent(txtDate)
                        .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addComponent(txtPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(879, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblNameErr, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEIDErr, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAgeErr)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblGenderErr, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblStartDateErr, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(drpdwnGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(lblLevelErr, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblTeamInfoErr, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPositionTitleErr, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblPhoneNumberErr, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEmailAddressErr, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhotoErr))
                .addGap(34, 34, 34)
                .addComponent(btnSave)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(180, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeamInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeamInfoActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddressActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        check=0;
        String Name="";
        int EmployeeID=0;
        int Age=0;
        String Gender="";
        String StartDate="";
        String Level="";
        String TeamInfo="";
        String PositionTitle="";
        long PhoneNumber=0;
        String EmailAddress="";
        String Photo="";
        if(txtName.getText().length()==0){
            lblNameErr.setText("Please enter the employee name");
        }
        else{
            Name = txtName.getText();
            lblNameErr.setText("");
            check++;
        }
        if(txtID.getText().length()==0){
            lblEIDErr.setText("Please enter the employee ID");
        }
        else{
            EmployeeID = Integer.parseInt(txtID.getText());
            lblEIDErr.setText("");
            check++;
        }
        if(txtAge.getText().length()==0){
            lblAgeErr.setText("Please enter the employee age");
        }
        else{
            Age = Integer.parseInt(txtAge.getText());
            lblAgeErr.setText("");
            check++;
        }
        if(drpdwnGender.getSelectedItem()=="-Select-"){
           lblGenderErr.setText("Please select the gender");           
       }
       else{
            Gender = String.valueOf(drpdwnGender.getSelectedItem());
            lblGenderErr.setText("");
            check++;
        }
        if(txtDate.getText().length()==0){
            lblStartDateErr.setText("Please enter the employee start date");
        }
        else{
            StartDate = txtDate.getText();
            lblStartDateErr.setText("");
            check++;
        }
        if(txtLevel.getText().length()==0){
            lblLevelErr.setText("Please enter the employee level");
        }
        else{
            Level = txtLevel.getText();
            lblLevelErr.setText("");
            check++;
        }
        if(txtTeamInfo.getText().length()==0){
            lblTeamInfoErr.setText("Please enter the employee team info");
        }
        else{
            TeamInfo = txtTeamInfo.getText();
            lblTeamInfoErr.setText("");
            check++;
        }
        if(txtPositionTitle.getText().length()==0){
            lblPositionTitleErr.setText("Please enter the employee position title");
        }
        else{
            PositionTitle = txtPositionTitle.getText();
            lblPositionTitleErr.setText("");
            check++;
        }
        if(txtPhoneNumber.getText().length()==0){
            lblPhoneNumberErr.setText("Please enter the employee phone number");
        }
        else{
            PhoneNumber = Long.parseLong(txtPhoneNumber.getText());
            lblPhoneNumberErr.setText("");
            check++;
        }
        if(txtEmailAddress.getText().length()==0){
            lblEmailAddressErr.setText("Please enter the employee email ID");
        }
        else{
            EmailAddress = txtEmailAddress.getText();
            lblEmailAddressErr.setText("");
            check++;
        }
        if(txtPhoto.getText().length()==0){
            lblPhotoErr.setText("Select the employee photo");
        }
        else{
            Photo = txtPhoto.getText();
            lblPhotoErr.setText("");
            check++;
        }
       
        if(check==11){Profile pro = history.addNewProfile();
        pro.setName(Name);
        pro.setEmployeeID(EmployeeID);
        pro.setAge(Age);
        pro.setGender(Gender);
        pro.setStartDate(StartDate);
        pro.setLevel(Level);
        pro.setTeamInfo(TeamInfo);
        pro.setPositionTitle(PositionTitle);
        pro.setPhoneNumber(PhoneNumber);
        pro.setEmailAddress(EmailAddress);
        pro.setPhoto(Photo);
        
        JOptionPane.showMessageDialog(this, "New Profile Added Successfully!");
            
        txtName.setText("");
        txtID.setText("");
        txtAge.setText("");
        drpdwnGender.setSelectedIndex(0);
        txtDate.setText("");
        txtLevel.setText("");
        txtTeamInfo.setText("");
        txtPositionTitle.setText("");
        txtPhoneNumber.setText("");
        txtEmailAddress.setText("");
        txtPhoto.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this,"Please enter the mandatory fields"); 
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLevelActionPerformed

    private void txtPositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionTitleActionPerformed

    private void btnPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhotoActionPerformed
        // TODO add your handling code here:
        PhotoFileChooser.setCurrentDirectory(new File("/Users/admin/Documents/ProfilePics"));
        int Value = PhotoFileChooser.showOpenDialog(this);
        if(Value==JFileChooser.APPROVE_OPTION){
              txtPhoto.setText( PhotoFileChooser.getSelectedFile().toString()); 
              
        }
        else{
            txtPhoto.setText("No File Selected");
        }
    }//GEN-LAST:event_btnPhotoActionPerformed

    private void txtPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhotoActionPerformed

    private void drpdwnGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpdwnGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpdwnGenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPhoto;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> drpdwnGender;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAgeErr;
    private javax.swing.JLabel lblContactInfo;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEIDErr;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEmailAddressErr;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGenderErr;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblLevelErr;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameErr;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumberErr;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPhotoErr;
    private javax.swing.JLabel lblPositionTitle;
    private javax.swing.JLabel lblPositionTitleErr;
    private javax.swing.JLabel lblStartDateErr;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JLabel lblTeamInfoErr;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPhoto;
    private javax.swing.JTextField txtPositionTitle;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables
}
