/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Employee.Profile;
import Employee.ProfileHistory;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class SearchJPanel extends javax.swing.JPanel {
     ProfileHistory history;

    /**
     * Creates new form SearchJPanel
     */
    public SearchJPanel(ProfileHistory history) {
        initComponents();
        this.history = history;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSerialNum = new javax.swing.JLabel();
        txtSerialNum = new javax.swing.JTextField();
        lblSearchProfiles = new javax.swing.JLabel();
        btnListAllProfiles = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfile = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmployeeID = new javax.swing.JTextField();
        lblEmployeeID = new javax.swing.JLabel();

        lblSerialNum.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblSerialNum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSerialNum.setText("Serial Number");

        txtSerialNum.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtSerialNum.setPreferredSize(new java.awt.Dimension(180, 30));
        txtSerialNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumActionPerformed(evt);
            }
        });

        lblSearchProfiles.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblSearchProfiles.setText("Search Profiles");

        btnListAllProfiles.setText("List All Profiles");
        btnListAllProfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllProfilesActionPerformed(evt);
            }
        });

        tblProfile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Employee ID", "Age", "Gender", "Start Date", "Level", "Team Info", "Position Title", "Phone Number", "Email Address"
            }
        ));
        jScrollPane1.setViewportView(tblProfile);

        lblName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("Name:");

        txtName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtName.setPreferredSize(new java.awt.Dimension(180, 30));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtEmployeeID.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtEmployeeID.setPreferredSize(new java.awt.Dimension(180, 30));
        txtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDActionPerformed(evt);
            }
        });

        lblEmployeeID.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblEmployeeID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmployeeID.setText("Employee ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(443, 443, 443)
                                .addComponent(lblSearchProfiles))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnListAllProfiles))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEmployeeID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 428, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblSearchProfiles)
                .addGap(18, 18, 18)
                .addComponent(btnListAllProfiles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEmployeeID)
                                .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblName)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnListAllProfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllProfilesActionPerformed
        // TODO add your handling code here
        populateTable();
    }//GEN-LAST:event_btnListAllProfilesActionPerformed

    private void txtSerialNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Employee = (DefaultTableModel) tblProfile.getModel();
        Employee.setRowCount(0);        
        for(Profile pro : history.getHistory()){
            Object[] row = new Object[10];
            row[0] = pro.getName();
            row[1] = pro.getEmployeeID();
            row[2] = pro.getAge();
            row[3] = pro.getGender();
            row[4] = pro.getStartDate();
            row[5] = pro.getLevel();
            row[6] = pro.getTeamInfo();
            row[7] = pro.getPositionTitle();
            row[8] = pro.getPhoneNumber();
            row[9] = pro.getEmailAddress();
                if(pro.getName().equals(txtName.getText())){
                    Employee.addRow(row);   
                }
        } 
        txtName.setText("");
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Employee = (DefaultTableModel) tblProfile.getModel();
        Employee.setRowCount(0);        
        for(Profile pro : history.getHistory()){
            Object[] row = new Object[10];
            row[0] = pro.getName();
            row[1] = pro.getEmployeeID();
            row[2] = pro.getAge();
            row[3] = pro.getGender();
            row[4] = pro.getStartDate();
            row[5] = pro.getLevel();
            row[6] = pro.getTeamInfo();
            row[7] = pro.getPositionTitle();
            row[8] = pro.getPhoneNumber();
            row[9] = pro.getEmailAddress();
                if(pro.getEmployeeID()==Integer.parseInt(txtEmployeeID.getText())){
                    Employee.addRow(row);   
                }
        } 
        txtEmployeeID.setText("");
    }//GEN-LAST:event_txtEmployeeIDActionPerformed

private void populateTable() {
        DefaultTableModel Employee = (DefaultTableModel) tblProfile.getModel();
        Employee.setRowCount(0);
        for (Profile pro : history.getHistory()){
            Object[] row = new Object[10];
            row[0] = pro;
            row[1] = pro.getEmployeeID();
            row[2] = pro.getAge();
            row[3] = pro.getGender();
            row[4] = pro.getStartDate();
            row[5] = pro.getLevel();
            row[6] = pro.getTeamInfo();
            row[7] = pro.getPositionTitle();
            row[8] = pro.getPhoneNumber();
            row[9] = pro.getEmailAddress();
            Employee.addRow(row);
        }
           
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListAllProfiles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSearchProfiles;
    private javax.swing.JLabel lblSerialNum;
    private javax.swing.JTable tblProfile;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSerialNum;
    // End of variables declaration//GEN-END:variables
}
