/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.Customer.Customer;
import Business.Customer.Hospital;
import Business.Customer.HospitalDirectory;
import Business.Customer.Patients;
import Business.Customer.PatientsDirectory;
import Business.Doctor.Doctor;
import Business.EcoSystem;
import Business.Encounter.EncounterHistory;
import Business.Menu.Item;
import Business.Menu.Menu;
import Business.Order.Order;
import Business.Restaurant.Restaurant;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class PatientAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    PatientsDirectory patD;
    EncounterHistory encH;
    HospitalDirectory Hd;
    ArrayList<String> patientsNames;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public PatientAreaJPanel(JPanel userProcessContainer,
                            UserAccount account ,EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = account;
        this.patD = system.getPatientsDirectory();
         this.encH = system.getEncounterHistory();
         this.Hd = system.getHospitalDirectory();
        valueLabel.setText(account.getUsername());
        ArrayList<Patients> PatientsList = this.system.getPatientsDirectory().returnPatientsDetails();
        patientsNames = new ArrayList<>();
        for(Patients p : PatientsList){
            patientsNames.add(p.getName());
        }
//        CbxCity.setModel(new DefaultComboBoxModel<String>(patientsNames.toArray(new String[0])));
//        populateMenuTable(PatientsList);
//        populateRequestTable();
    }
    
    public void populateMenuTable(ArrayList<Patients> PatientsList){
//        String patientsName = comboRestaurant.getSelectedItem().toString();
//        ArrayList<Item> itemList = new ArrayList();
//        for(Patients p : PatientsList){
//            if(p.getName().equals(patientsName)){
//                itemList = p.getMenu().getMenu();
//                break;
//            }
//        }
//        
//        System.out.println("Inside method to populate Menu table");
//        DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();
//        model.setRowCount(0);
//
//        for(Item item : itemList){
//            System.out.println(item);
//            Object[] row = new Object[2];
//            row[0] = item;
//            row[1] = item.getPrice();
//            model.addRow(row);
//        }
    }
    
    public void populateRequestTable(){
//        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
//        model.setRowCount(0);
//        for (Order order : system.getOrderDirectory().getOrderDirectory()){
//            //System.out.println("Order" + order.getOrderId());
//            if(userAccount.getPatient().getName().equals(order.getPatients().getName())) {
//                Object[] row = new Object[8];
//                row[0] = order;
//                row[1] = order.getItem().getItemName();
//                row[2] = order.getQuantity() * order.getItem().getPrice();
//                row[3] = order.getRestaurant().getRestaurantName();
//                row[4] = order.getMessage();
//                row[5] = order.getCustomer().getName();
//                row[6] = order.getOrderStatus();
//                row[7] = order.getQuantity();
//                model.addRow(row);
//            }
//        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CbxCity = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        CbxCommunity = new javax.swing.JComboBox();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Welcome ");

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setText("<value>");

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Doctor Name", "Address", "Phone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMenu);

        jLabel1.setText("Select City :");

        CbxCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Select --", "Boston", "New York" }));
        CbxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxCityActionPerformed(evt);
            }
        });

        jLabel4.setText("Select Community :");

        CbxCommunity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Select --", "Mission Hill", "Jamaica Plain", "Huntington Avenue", "Bolyston" }));
        CbxCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxCommunityActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(CbxCity, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearch)
                                    .addComponent(CbxCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CbxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CbxCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnSearch)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CbxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxCityActionPerformed

    private void CbxCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxCommunityActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();
        model.setRowCount(0);
        for(Hospital H: Hd.returnHospitalDetails()){
            
            String comm = (String)CbxCommunity.getSelectedItem();
            String city = (String)CbxCity.getSelectedItem();
            
            for(Doctor d: H.returnDoctorDetails()){
                
                if(comm == H.getCommunity() && city == H.getCity()){
                    Object[] row = new Object[4];
                    row[0] = H;
                    row[1] = d;
                    row[2] = H.getAddress();
                    
                    row[3] = H.getPhoneNumber();
                    model.addRow(row);
            }
            }
        }
        
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CbxCity;
    private javax.swing.JComboBox CbxCommunity;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMenu;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
